// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChildrenController from "./children_controller"
application.register("children", ChildrenController)

import CommentFormsButtonController from "./comment_forms_button_controller"
application.register("comment-forms-button", CommentFormsButtonController)

import CommentToggleController from "./comment_toggle_controller"
application.register("comment-toggle", CommentToggleController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
